name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --filter Category=UnitTest --no-restore --verbosity normal

    - name: Generate coverage report
      run: dotnet test --filter Category=UnitTest --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

    - name: Pack NuGet-Package
      run: dotnet pack --configuration Release --no-restore --no-build --output nupkgs

    - name: Get NuGet-Package Name
      id: get_package_name
      shell: bash
      run: |
        PACKAGE_NAME=$(ls nupkgs/*.nupkg)
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

    - name: Upload NuGet-Package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path:  ${{ env.PACKAGE_NAME }}

    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@v1.0.1   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./Develappers.RedmineHourglassApi.Tests/TestResults/coverage.info  
